#!/usr/bin/env bash
#
# OrthoAppeals — one-shot stand-up for a fresh Ubuntu 22.04/24.04 box.
#
# What it does, in order:
#   1. installs Python + Caddy (automatic HTTPS)
#   2. puts the app in /opt/orthoappeals and installs its Python deps
#   3. creates the secrets file at /etc/mdplus/mdplus.env (chmod 600)
#   4. installs + starts the systemd services (app, nightly purge, backup)
#   5. points Caddy at your domain and turns on HTTPS
#
# Run it as root on a fresh box:
#     sudo bash setup.sh
#
# It is safe to re-run: it updates in place and never overwrites your secrets
# file once it exists.
#
set -euo pipefail

APP_DIR="/opt/orthoappeals"
ENV_DIR="/etc/mdplus"
ENV_FILE="${ENV_DIR}/mdplus.env"
SERVICE_USER="orthoapp"
REPO_DEFAULT="https://github.com/andrewbouras/mdplus-denial-agent-lab.git"

say() { printf "\n\033[1;36m==> %s\033[0m\n" "$*"; }
die() { printf "\n\033[1;31mERROR: %s\033[0m\n" "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run this as root:  sudo bash setup.sh"

# ---- 0. inputs --------------------------------------------------------------
DOMAIN="${ORTHO_DOMAIN:-}"
REPO="${ORTHO_REPO:-$REPO_DEFAULT}"
if [ -z "$DOMAIN" ]; then
  read -rp "Your domain (e.g. orthoappeals.com), already pointed at this server's IP: " DOMAIN
fi
[ -n "$DOMAIN" ] || die "A domain is required for HTTPS."

# ---- 1. packages ------------------------------------------------------------
say "Installing system packages (Python, git, Caddy)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y python3 python3-pip python3-venv git curl debian-keyring debian-archive-keyring apt-transport-https
if ! command -v caddy >/dev/null 2>&1; then
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -y
  apt-get install -y caddy
fi

# ---- 2. app + deps ----------------------------------------------------------
say "Installing the app into ${APP_DIR}"
id "$SERVICE_USER" >/dev/null 2>&1 || useradd --system --create-home --shell /usr/sbin/nologin "$SERVICE_USER"
if [ -d "${APP_DIR}/.git" ]; then
  git -C "$APP_DIR" pull --ff-only
else
  git clone --depth 1 "$REPO" "$APP_DIR"
fi
python3 -m venv "${APP_DIR}/.venv"
"${APP_DIR}/.venv/bin/pip" install --upgrade pip
# The providers extra pulls the Anthropic SDK (and OpenAI/Google if you use them).
"${APP_DIR}/.venv/bin/pip" install -e "${APP_DIR}[providers]" || \
  "${APP_DIR}/.venv/bin/pip" install anthropic
chown -R "$SERVICE_USER:$SERVICE_USER" "$APP_DIR"

# ---- 3. secrets -------------------------------------------------------------
say "Setting up the secrets file at ${ENV_FILE}"
mkdir -p "$ENV_DIR"
if [ ! -f "$ENV_FILE" ]; then
  cp "${APP_DIR}/deploy/mdplus.env.example" "$ENV_FILE"
  # Generate an encryption key so uploads/records are sealed at rest by default.
  KEY="$(python3 -c 'import secrets,base64;print(base64.b64encode(secrets.token_bytes(32)).decode())')"
  {
    echo ""
    echo "# --- generated by setup.sh ---"
    echo "MDPLUS_ENCRYPTION_KEY=${KEY}"
    echo "MDPLUS_TRUST_PROXY=true"
    echo "# Daily spend cap in USD for this free public site. Reads/appeals stop"
    echo "# for the day once this is hit, then resume tomorrow. Tune as you like."
    echo "MDPLUS_DAILY_BUDGET_USD=${ORTHO_DAILY_BUDGET_USD:-50}"
  } >> "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo
  echo ">>> ACTION NEEDED: put your Anthropic API key in ${ENV_FILE}"
  echo ">>>   sudo nano ${ENV_FILE}      and set ANTHROPIC_API_KEY=sk-ant-..."
  echo ">>> (Optional: OPENAI_API_KEY / GOOGLE_API_KEY for the multi-model comparison.)"
else
  echo "Secrets file already exists — leaving it untouched."
fi

# ---- 4. systemd services ----------------------------------------------------
say "Installing systemd services"
# Rewrite the unit files to use this box's user + path, then install them.
render_unit() {
  sed -e "s#/home/clawd/mdplus-denial-agent-lab#${APP_DIR}#g" \
      -e "s#^User=clawd#User=${SERVICE_USER}#" \
      -e "s#^Group=clawd#Group=${SERVICE_USER}#" \
      -e "s#/usr/bin/python3#${APP_DIR}/.venv/bin/python#g" \
      "$1"
}
render_unit "${APP_DIR}/deploy/mdplus-harness.service" > /etc/systemd/system/orthoappeals.service
for u in mdplus-purge.service mdplus-purge.timer mdplus-backup.service mdplus-backup.timer; do
  [ -f "${APP_DIR}/deploy/${u}" ] && render_unit "${APP_DIR}/deploy/${u}" > "/etc/systemd/system/${u}"
done
systemctl daemon-reload
systemctl enable --now orthoappeals.service
for t in mdplus-purge.timer mdplus-backup.timer; do
  [ -f "/etc/systemd/system/${t}" ] && systemctl enable --now "$t" || true
done

# ---- 5. Caddy / HTTPS -------------------------------------------------------
say "Configuring HTTPS for ${DOMAIN}"
sed "s/appeals.example.com/${DOMAIN}/" "${APP_DIR}/deploy/Caddyfile.example" > /etc/caddy/Caddyfile
systemctl reload caddy || systemctl restart caddy

say "Done."
cat <<EOF

OrthoAppeals is installed.

  App service : systemctl status orthoappeals
  Logs        : journalctl -u orthoappeals -f
  Secrets     : ${ENV_FILE}
  Site        : https://${DOMAIN}/

If you have NOT put your Anthropic key in yet:
  1. sudo nano ${ENV_FILE}       # set ANTHROPIC_API_KEY=...
  2. sudo systemctl restart orthoappeals

Caddy will fetch the HTTPS certificate automatically the first time someone
visits https://${DOMAIN}/ (make sure the domain's DNS points at this server).
EOF
