#!/usr/bin/env python3
"""Generate mockups/assets/submit.js from the appeal-submission routes.

Member appeal routes researched from each insurer's own site or official
form, keyed by lowercase match tokens. The app's submitFor() checks this
extended directory first, then the small hand-written set in data.js, then
the honest generic. A low-confidence route ships only its safe parts (phone,
'use your denial letter') -- never a guessed address.
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
src = json.loads((ROOT/'data/policy_platform/appeal_submission_routes.json').read_text())

out = {}
for r in src['routes']:
    entry = {
        'insurer': r['insurer'],
        'portal': r['portal'] or None,
        'phone': r['phone'] or 'The number on the back of your insurance card',
        'fax': r['fax'] or None,
        'mail': r['mail'] or 'The appeal address printed on your denial letter',
        'how': r['how'],
        'window': r['window'] or 'Check your denial letter — it states your exact deadline',
        'source': r['source_url'],
        'confidence': r['confidence'],
    }
    if r.get('ma_note'):
        entry['ma_note'] = r['ma_note']
    for token in r['match']:
        out[token] = entry

js = ("// GENERATED by scripts/build_submit_js.py — do not hand-edit.\n"
      "// Member appeal-submission routes, from each insurer's own site.\n"
      "// The denial letter is always authoritative; this is the fallback\n"
      "// plus the online/phone options.\n"
      "window.APPEAL_SUBMIT_EXT = " + json.dumps(out, indent=1) + ";\n")
p = ROOT/'mockups/assets/submit.js'
p.write_text(js)
print(f"wrote {p} ({len(js)//1024} KB), {len(out)} match keys, "
      f"{len(src['routes'])} insurers")
