#!/usr/bin/env python3
"""Generate mockups/assets/coverage.js from the app-option policy directory.

Gives the frontend an honest, compact answer for every option combo the site
offers: do we hold the governing policy document for this surgery + state +
insurer, and if so where is it?  Codes:
  V = verified public policy document on file (url present)
  L = Medicare: no LCD exists — general medical-necessity standards apply
  N = insurer keeps criteria in a private tool (InterQual/MCG/eviCore portal...)
  G = document exists but behind a login
  F = nothing on file (not found / not yet researched)
  C/S/U = code-list only / stale / unreachable  (treated like F in the UI)
"""
import csv, json, collections, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
rows = list(csv.DictReader(open(ROOT/'data/policy_platform/app_option_policy_directory.csv')))

def code(status):
    s = status
    if s.startswith('VERIFIED'): return 'V'
    if s.startswith('NO LCD'): return 'L'
    if 'NO PUBLIC CRITERIA' in s: return 'N'
    if s.startswith('GATED'): return 'G'
    if s.startswith('CODE ONLY'): return 'C'
    if s.startswith('STALE'): return 'S'
    if s.startswith('UNREACHABLE'): return 'U'
    return 'F'

urls = {}
def uix(u):
    if not u: return -1
    if u not in urls: urls[u] = len(urls)
    return urls[u]

comm = {}      # "insurer|cpt" -> [code, urlIdx, title]
medicare = {}  # "state|cpt"   -> [code, urlIdx, title]
medicaid = {}  # "state|cpt"   -> [code, urlIdx, title]
for r in rows:
    c = code(r['status'])
    if c == 'F':
        continue  # default in the UI; omitting keeps the file small
    ent = [c, uix(r['policy_url']) if c == 'V' else -1, (r['policy_title'] or '')[:60] if c == 'V' else '']
    if r['insurance_company'] == 'Medicare':
        medicare[f"{r['state']}|{r['cpt']}"] = ent
    elif r['insurance_company'] == 'Medicaid':
        medicaid[f"{r['state']}|{r['cpt']}"] = ent
    else:
        k = f"{r['insurance_company']}|{r['cpt']}"
        if k not in comm or (c=='V' and comm[k][0]!='V'):
            comm[k] = ent

url_list = [u for u,_ in sorted(urls.items(), key=lambda x: x[1])]
payload = {'urls': url_list, 'comm': comm, 'medicare': medicare, 'medicaid': medicaid}
js = ("// GENERATED by scripts/build_coverage_js.py — do not hand-edit.\n"
      "// Honest per-option coverage: which governing policy documents we hold.\n"
      "window.APPEAL_COVERAGE = " + json.dumps(payload, separators=(',',':')) + ";\n")
out = ROOT/'mockups/assets/coverage.js'
out.write_text(js)
stats = collections.Counter(v[0] for v in list(comm.values())+list(medicare.values())+list(medicaid.values()))
print(f"wrote {out} ({len(js)//1024} KB) | entries comm={len(comm)} medicare={len(medicare)} medicaid={len(medicaid)} | codes={dict(stats)}")
